makeUI_mainPage_and_loginPage
KCCT-D4-2024/Entrion pull request #10
Opened 2024-10-18 07:44 UTC by asdf969

UI作ったよ

2024-10-18 08:23 UTC, Hayatann requested changes

2024-10-18 08:23 UTC, Hayatann commented on app/views/layouts/application.html.erb
> +    <!-- Tailwind CSS -->
ライブラリ側で導入してるからここはいらんはず

2024-10-18 08:23 UTC, Hayatann commented on app/views/tests/index.html.erb
> +      <p>君じゃ無理だよ...</p>
?

2024-10-20 05:04 UTC, asdf969 commented
レビューで言われていた箇所を消しました。

in /Entrion/app/views/layouts/application.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<!-- Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
これ全部消した

2024-10-20 08:27 UTC, asdf969 commented
UI更新したよ。
あとコメント直接見れなかったけど、Entrion/app/views/layouts/application.html.erbの２行目に<html data-theme="light">を追加した

2024-10-20 09:33 UTC, Hayatann approved these changes
LGTM

2024-10-20 09:33 UTC, Hayatann commented on app/views/layouts/application.html.erb
> -<html data-theme="light">
@asdf969 
これ消したら色合いが変わっちゃう気がする
変わらんかったら大丈夫

2024-10-20 09:34 UTC, Hayatann commented
コンフリクトを解決していただきたい
schema.rbは　https://qiita.com/jnchito/items/494a0499b808f109e0a8
これみてもらって

2024-10-21 07:54 UTC, merged